security:
    encoders:
        App\Domain\Player\Player:
            algorithm: bcrypt
    providers:
        users:
            entity:
                class: 'App\Domain\Player\Player'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/api/players
            stateless: true
            anonymous: true

        games:
            pattern:  ^/api/games
            stateless: true
            anonymous: true

        top-players:
            pattern:  ^/api/top-players
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            provider: users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/players,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/top-players,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/games,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
